### ISSUE TITLE
Error of running the examples

### ISSUE THREAD

**Issue by OliverZijia** [icarus-sim/icarus#17]
Hi, 

When I try to run the examples in the example folder (lce-vs-probcache) with command "icarus run --results test.pickle config.py", I got this error:

Traceback (most recent call last):
  File "/zijia/RL-NDN/Icarus/icarus/icarus/scenarios/workload.py", line 121, in __iter__
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zijia/RL-NDN/Icarus/icarus/icarus/orchestration.py", line 279, in run_scenario
    results = exec_experiment(topology, workload, netconf, strategy, cache_policy, collectors)
  File "/zijia/RL-NDN/Icarus/icarus/icarus/execution/engine.py", line 59, in exec_experiment
    for time, event in workload:
RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/icarus", line 33, in <module>
    sys.exit(load_entry_point('icarus', 'console_scripts', 'icarus')())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/zijia/RL-NDN/Icarus/icarus/icarus/main.py", line 42, in run
    icarus.run(config, results, config_override)
  File "/zijia/RL-NDN/Icarus/icarus/icarus/runner.py", line 112, in run
    orch.run()
  File "/zijia/RL-NDN/Icarus/icarus/icarus/orchestration.py", line 126, in run
    self.n_exp))
  File "/zijia/RL-NDN/Icarus/icarus/icarus/orchestration.py", line 289, in run_scenario
    err_type = str(type(e)).split("'")[1].split(".")[1]
IndexError: list index out of range

Also, when I run offpath-vs-onpath-caching example, I got something like this:

[06:30:59 2020-07-02|INFO|runner-ForkPoolWorker-7] Experiment 251/1536 | Start simulation
[06:30:59 2020-07-02|ERROR|orchestration] FAILURE | Experiment failed: list index out of range
[06:30:59 2020-07-02|ERROR|orchestration] FAILURE | Experiment failed: list index out of range
[06:31:00 2020-07-02|ERROR|orchestration] FAILURE | Experiment failed: list index out of range

Could you tell me what should I do to fix this issue? Thank you!

**Comment by OliverZijia** [comment]
Hi, another quick question which may also be related to the first one, after I completing the offpath-vs-onpath-caching example, I got test.pickle, but when I tried to print it using .prettyprint(), the output is empty.

Could you tell me what should I do?

Have a good day!

**Comment by lorenzosaino** [comment]
Hello,

That was a bug that emerged in Python 3.7. I pushed a fix for that. If you pull Icarus and re-install it, it should work fine. As for the list of results being empty, that's expected because the experiments failed and therefore no results were added.

I am closing this issue for now. Feel free to reopen it if the problem persists.
