### ISSUE TITLE
Issue while running the simulation

### ISSUE THREAD

**Issue by madhucharan** [icarus-sim/icarus#24]
- Hello, I am facing this issue while running the simulation, could you guide me through it on running a simulation on windows

(icarus) D:\icarus>icarus run --results results.pkl config.py
Traceback (most recent call last):
  File "G:\envs\icarus\Scripts\icarus-script.py", line 11, in <module>
    load_entry_point('icarus==0.8.0', 'console_scripts', 'icarus')()
  File "G:\envs\icarus\lib\site-packages\click-8.0.0a1-py3.8.egg\click\core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "G:\envs\icarus\lib\site-packages\click-8.0.0a1-py3.8.egg\click\core.py", line 955, in main
    rv = self.invoke(ctx)
  File "G:\envs\icarus\lib\site-packages\click-8.0.0a1-py3.8.egg\click\core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "G:\envs\icarus\lib\site-packages\click-8.0.0a1-py3.8.egg\click\core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\envs\icarus\lib\site-packages\click-8.0.0a1-py3.8.egg\click\core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "G:\envs\icarus\lib\site-packages\icarus-0.8.0-py3.8.egg\icarus\main.py", line 42, in run
    icarus.run(config, results, config_override)
  File "G:\envs\icarus\lib\site-packages\icarus-0.8.0-py3.8.egg\icarus\runner.py", line 109, in run
    for sig in (signal.SIGTERM, signal.SIGINT, signal.SIGHUP, signal.SIGQUIT, signal.SIGABRT):
AttributeError: module 'signal' has no attribute 'SIGHUP'

**Comment by lorenzosaino** [comment]
Hi Madhu, running Icarus on Windows is not supported. If you wish to implement Windows support yourself, I'd be happy to accept pull requests. If you'd rather not, then I'd recommend to install Docker and run Icarus inside a Docker container. Icarus ships a Dockerfile that you can use to create a Docker image: https://github.com/icarus-sim/icarus/blob/master/Dockerfile
