### ISSUE TITLE
Problem in running PyResonance

### ISSUE THREAD

**Issue by royreshma** [icarus-sim/icarus#5]
I had installed PyResonance and related packages as per Github.
When i try to run PyResonance i get an error as follows:

mininet@mininet-vm:~/pyretic$ pyretic.py pyretic.pyresonance.main --config=./pyretic/pyresonance/global.config --mode=manual

*** Specified Modules are: ***

  pyretic.pyresonance.apps.auth (auth)

  pyretic.pyresonance.apps.ids (ids)

*** The Policy Composition is: ***
auth >> ids

start-frenetic.sh: line 5: ./frenetic: No such file or directory
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
Connected to pyretic frontend.
INFO:core:POX 0.2.0 (carp) is up.
INFO:openflow.of_01:[00-00-00-00-00-01 3] connected
INFO:openflow.of_01:[00-00-00-00-00-03 1] connected
INFO:openflow.of_01:[00-00-00-00-00-02 2] connected
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mininet/pyretic/pyretic/core/runtime.py", line 2326, in f
    self.runtime.handle_network_change()
  File "/home/mininet/pyretic/pyretic/core/runtime.py", line 465, in handle_network_change
    self.update_switch_classifiers()
  File "/home/mininet/pyretic/pyretic/core/runtime.py", line 553, in update_switch_classifiers
    classifier = self.whole_policy_compile()
  File "/home/mininet/pyretic/pyretic/evaluations/stat.py", line 158, in profiled_func
    res = func(*args, **kwargs)
  File "/home/mininet/pyretic/pyretic/evaluations/stat.py", line 109, in profiled_func
    res = func(*args, **kwargs)
  File "/home/mininet/pyretic/pyretic/core/runtime.py", line 514, in whole_policy_compile
    p = cp.netkat_compile(self.sw_cnt())[0] # directly compile with netkat
  File "/home/mininet/pyretic/pyretic/core/language.py", line 186, in netkat_compile
    server_port=server_port)
  File "/home/mininet/pyretic/pyretic/core/netkat.py", line 158, in generate_classifier
    (cls_json, ctime) = httplib_channel_compilation(pol)
  File "/home/mininet/pyretic/pyretic/core/netkat.py", line 126, in httplib_channel_compilation
    json_input = compile_to_netkat(pol)
  File "/home/mininet/pyretic/pyretic/core/netkat.py", line 494, in compile_to_netkat
    return json.dumps(to_pol(pyretic_pol))
  File "/home/mininet/pyretic/pyretic/core/netkat.py", line 423, in to_pol
    from pyretic.evaluations.Tests.common_modules.stanford_forwarding import StanfordForwarding
  File "/home/mininet/pyretic/pyretic/evaluations/Tests/__init__.py", line 6, in <module>
    module = loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/mininet/pyretic/pyretic/evaluations/Tests/congested_link/__init__.py", line 6, in <module>
    module = loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/mininet/pyretic/pyretic/evaluations/Tests/congested_link/Topos/__init__.py", line 6, in <module>
    module = loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/mininet/pyretic/pyretic/evaluations/Tests/congested_link/Topos/FatTree.py", line 1, in <module>
    import fnss
ImportError: No module named fnss

**Comment by lorenzosaino** [comment]
You must have opened this issue on the wrong project. Icarus project has nothing to do with PyResonance. Open an issue with PyResonance
